dzielnice_dict = {'Bemowo': ['Bemowo Lotnisko',
  'Boernerowo',
  'Chrzanów',
  'Fort Bema',
  'Fort Radiowo',
  'Górce',
  'Groty',
  'Jelonki Południowe',
  'Jelonki Północne',
  'Lotnisko'],
 'Białołęka': ['Białołęka Dworska',
  'Brzeziny',
  'Choszczówka',
  'Dąbrówka Szlachecka',
  'Grodzisk',
  'Henryków',
  'Kobiałka',
  'Nowodwory',
  'Szamocin',
  'Tarchomin',
  'Żerań'],
 'Bielany': ['Chomiczówka',
  'Huta',
  'Las Bielański',
  'Marymont-Kaskada',
  'Marymont-Ruda',
  'Młociny',
  'Piaski',
  'Placówka',
  'Radiowo',
  'Słodowiec',
  'Stare Bielany',
  'Wawrzyszew',
  'Wólka Węglowa',
  'Wrzeciono'],
 'Mokotów': ['Augustówka',
  'Czerniaków',
  'Ksawerów',
  'Sadyba',
  'Siekierki',
  'Sielce',
  'Służew',
  'Służewiec',
  'Stary Mokotów',
  'Stegny',
  'Wierzbno',
  'Wyględów'],
 'Ochota': ['Filtry', 'Rakowiec', 'Stara Ochota', 'Szczęśliwice'],
 'Praga-Południe': ['Gocław',
  'Gocławek',
  'Grochów',
  'Kamionek',
  'Olszynka Grochowska',
  'Saska Kępa'],
 'Praga-Północ': ['Nowa Praga', 'Pelcowizna', 'Stara Praga', 'Szmulowizna'],
 'Rembertów': ['Kawęczyn-Wygoda', 'Nowy Rembertów', 'Stary Rembertów'],
 'Śródmieście': ['Muranów',
  'Nowe Miasto',
  'Powiśle',
  'Solec',
  'Stare Miasto',
  'Śródmieście Południowe',
  'Śródmieście Północne',
  'Ujazdów'],
 'Targówek': ['Bródno',
  'Bródno-Podgrodzie',
  'Elsnerów',
  'Targówek Fabryczny',
  'Targówek Mieszkaniowy',
  'Utrata',
  'Zacisze'],
 'Ursus': ['Czechowice', 'Gołąbki', 'Niedźwiadek', 'Skorosze', 'Szamoty'],
 'Ursynów': ['Dąbrówka',
  'Grabów',
  'Jeziorki Południowe',
  'Jeziorki Północne',
  'Kabaty',
  'Las Kabacki',
  'Natolin',
  'Pyry',
  'Skarpa Powsińska',
  'Stary Imielin',
  'Stary Służew',
  'Ursynów Centrum',
  'Ursynów Północny',
  'Wyczółki'],
 'Wawer': ['Aleksandrów',
  'Anin',
  'Falenica',
  'Las',
  'Marysin Wawerski',
  'Miedzeszyn',
  'Międzylesie',
  'Nadwiśle',
  'Os.Wawer',
  'Radość',
  'Sadul',
  'Zerzeń'],
 'Wesoła': ['Groszówka',
  'Plac Wojska Polskiego',
  'Stara Miłosna',
  'Wesoła-Centrum',
  'Wola Grzybowska',
  'Zielona-Grzybowa'],
 'Wilanów': ['Błonia Wilanowskie',
  'Kępa Zawadowska',
  'Powsin',
  'Powsinek',
  'Wilanów Królewski',
  'Wilanów Niski',
  'Wilanów Wysoki',
  'Zawady'],
 'Włochy': ['Nowe Włochy',
  'Okęcie',
  'Opacz Wielka',
  'Paluch',
  'Raków',
  'Salomea',
  'Stare Włochy',
  'Załuski'],
 'Wola': ['Czyste',
  'Koło',
  'Mirów',
  'Młynów',
  'Nowolipki',
  'Odolany',
  'Powązki',
  'Ulrychów'],
 'Żoliborz': ['Marymont-Potok', 'Sady Żoliborskie', 'Stary Żoliborz']}